using AIM.Models;
using AIM.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using System.Collections.ObjectModel;
using System.IO;

namespace AIM.ViewModels;

public partial class MainViewModel : ObservableObject
{
    private readonly ISettingsService _settingsService;
    private readonly IFileService _fileService;

    // This attribute was missing. It generates the public 'SelectedRoot' property.
    [ObservableProperty]
    private string _selectedRoot;

    public ObservableCollection<DirectoryItem> LeftTree { get; } = new();
    public ObservableCollection<FileItem> SelectedScanFiles { get; } = new();

    public MainViewModel(ISettingsService settingsService, IFileService fileService)
    {
        _settingsService = settingsService;
        _fileService = fileService;

        var appSettings = _settingsService.LoadSettings();
        // This will now compile because 'LoadSettings' returns AppSettings.
        // And it will trigger the OnSelectedRootChanged method.
        SelectedRoot = appSettings.DefaultRootDirectory;
    }

    // This partial method's declaration is now generated by the [ObservableProperty] above.
    partial void OnSelectedRootChanged(string value)
    {
        var appSettings = _settingsService.LoadSettings();
        appSettings.DefaultRootDirectory = value;
        _settingsService.SaveSettings(appSettings);

        BuildTree();
    }

    private void BuildTree()
    {
        LeftTree.Clear();
        if (string.IsNullOrEmpty(SelectedRoot) || !Directory.Exists(SelectedRoot))
        {
            return;
        }

        var rootNode = new DirectoryItem
        {
            Name = Path.GetFileName(SelectedRoot),
            FullPath = SelectedRoot
        };

        _fileService.PopulateSubDirectories(rootNode);
        LeftTree.Add(rootNode);
    }
}