using System;
using System.Collections.Generic;

namespace AIM.Models;

// This class holds all the data for the printable form.
public class PrintableForm
{
    public string Header { get; set; }
    public string SubHeader { get; set; }
    public string Date { get; set; }
    public string GeneratedBy { get; set; }

    // THE FIX: Added OpCoHeader for the service class.
    public string OpCoHeader { get; set; }

    // This property will likely be used by the UI.
    public List<PrintableFormItem> Items { get; set; }

    // THE FIX: Added 'Pages' for the pagination logic in the service class.
    // It's a list of lists, where each inner list represents one page of items.
    public List<List<PrintableFormItem>> Pages { get; set; }

    public PrintableForm()
    {
        Header = "Inventory Summary";
        SubHeader = "Generated by AIM";
        Date = DateTime.Now.ToString("yyyy-MM-dd");
        GeneratedBy = Environment.UserName;
        OpCoHeader = string.Empty; // Initialize the new property
        Items = new List<PrintableFormItem>();
        Pages = new List<List<PrintableFormItem>>(); // Initialize the new property
    }
}