namespace AIM.Models;

/// <summary>
/// Represents a single displayable line in the final printable form.
/// </summary>
public class PrintableFormItem
{
    // THE FIX: These properties now match the data being generated by the service.
    public string Content { get; set; } = string.Empty;
    public RowType Type { get; set; }
}